import { ImageResponse } from "next/og";

export const alt = "RealEstateChatbot.ai lead conversion dashboard preview";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function Image() {
  return new ImageResponse(<div style={{ background: "#10231b", color: "white", width: "100%", height: "100%", display: "flex", padding: 54, fontFamily: "Arial, sans-serif" }}><div style={{ display: "flex", flexDirection: "column", justifyContent: "space-between", width: "42%" }}><div style={{ display: "flex", flexDirection: "column" }}><div style={{ fontSize: 28, fontWeight: 700 }}>RealEstateChatbot.ai</div><div style={{ marginTop: 24, fontSize: 58, lineHeight: 1.04, fontWeight: 800 }}>Turn real estate traffic into qualified appointments.</div></div><div style={{ color: "#b8d5c7", fontSize: 22 }}>Hosted links • Website widgets • QR codes • Follow-up</div></div><div style={{ marginLeft: 48, flex: 1, border: "1px solid rgba(255,255,255,0.18)", borderRadius: 24, overflow: "hidden", background: "#f5f7f2", color: "#162018", display: "flex", flexDirection: "column" }}><div style={{ height: 66, background: "#173f2f", color: "white", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 28px", fontSize: 22, fontWeight: 700 }}><span>Lead inbox</span><span style={{ color: "#f5c45b" }}>32 qualified</span></div><div style={{ display: "flex", padding: 28, gap: 18 }}>{[["Hot", "Buyer", "Winnipeg", "1 month"], ["Warm", "Seller", "River Heights", "Valuation"], ["New", "Open house", "QR channel", "Showing"]].map((row) => <div key={row.join("-")} style={{ flex: 1, border: "1px solid #d9ded2", borderRadius: 16, background: "white", padding: 18, display: "flex", flexDirection: "column", gap: 12 }}><div style={{ color: "#2861a8", fontSize: 20, fontWeight: 800 }}>{row[0]}</div><div style={{ fontSize: 26, fontWeight: 800 }}>{row[1]}</div><div style={{ color: "#657064", fontSize: 18 }}>{row[2]}</div><div style={{ marginTop: "auto", borderRadius: 999, background: "#f5c45b", padding: "8px 12px", fontSize: 16, fontWeight: 700 }}>{row[3]}</div></div>)}</div><div style={{ margin: "0 28px 28px", borderRadius: 16, background: "#edf3ea", padding: 20, display: "flex", gap: 20, color: "#334238", fontSize: 18 }}><span>Source: Website widget</span><span>Score: 92</span><span>Next: appointment</span></div></div></div>, size);
}
